# Generated by Django 2.1.8 on 2019-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sales',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(),
        ),
    ]
